# File: docker-compose.yml
services:
  vpn-proxy:
    image: ghcr.io/meek2100/gp-proxy:latest
    container_name: gp-proxy
    # OPTIONAL: Limit memory usage
    #mem_limit: 128m
    #memswap_limit: 128m
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
      # OPTIONAL: Keep connections alive at Kernel level
      #- net.ipv4.tcp_keepalive_time=60
      #- net.ipv4.tcp_keepalive_intvl=10
      #- net.ipv4.tcp_keepalive_probes=3
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_PORTAL=vpn.yourcompany.com
    # OPTIONAL: Use tmpfs to prevent log file creation
    #tmpfs:
    #  - /tmp:size=64M,mode=1777
    networks:
      gp_network:
        ipv4_address: 192.168.1.155
        mac_address: 02:F5:58:97:8E:88
    restart: unless-stopped

networks:
  gp_network:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1
